services:
  mysql:
    image: mysql:8.0
    container_name: btc_app_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init_btc_table.sql:/docker-entrypoint-initdb.d/init_btc_table.sql
    env_file:
      - .env
    ports:
      - "3307:3306"

  api:
    build: ./btc-backend
    container_name: btc_app_api
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./btc-backend/.env
    depends_on:
      - mysql

volumes:
  mysql-data:
    name: btc_app_mysql_data
  