CREATE TABLE IF NOT EXISTS btc_daily_prices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  price FLOAT NOT NULL,
  date DATE NOT NULL UNIQUE,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
