# Dockerfile.dev (para desenvolvimento)
FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copia todos os arquivos do projeto
COPY . .

EXPOSE 3000

# Inicia o servidor Next.js em modo desenvolvimento
CMD ["npm", "run", "dev"]