# Dockerfile.dev (para desenvolvimento)
FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copia todos os arquivos do projeto
COPY . .

# Gera o Prisma Client
RUN npx prisma generate --schema=src/infrastructure/database/prisma/schema.prisma

EXPOSE 3001

# Inicia o servidor em modo desenvolvimento com ts-node-dev
CMD ["npm", "run", "dev"]
