# Dockerfile.dev (para desenvolvimento)
FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copia todos os arquivos do projeto
COPY . .

# Gera o Prisma Client
RUN npx prisma generate --schema=src/infrastructure/database/prisma/schema.prisma

# Copia o script wait-for-it.sh
# COPY wait-for-it.sh ./wait-for-it.sh
# RUN chmod +x ./wait-for-it.sh

EXPOSE 3000

# Inicia o servidor em modo desenvolvimento com ts-node-dev
# CMD ["./wait-for-it.sh", "mysql:3306", "--", "npm", "run", "dev"]
CMD ["npm", "run", "dev"]
